'use strict';

const USER_PREFIX = 'NLBANK1|U|';
const MARKET_PREFIX = 'NLBANK1|M|';
const START_BALANCE = 1000;
const COMMAND_CD = 6 * 60 * 1000;
const SALARY_CD = COMMAND_CD;
const TIP_CD = COMMAND_CD;
const MARKET_STEP = 3 * 60 * 1000;
const LOAN_CD = 60 * 60 * 1000;
const LOAN_AMOUNT = 10000;
const MAX_BET = Number.MAX_VALUE;
const ROB_CD = 5 * 60 * 1000;
const PROTECTION_DURATION = 60 * 60 * 1000;
const clamp = (n,min,max)=>Math.max(min,Math.min(max,n));
function newUser(){return{balance:START_BALANCE,vault:0,shares:0,stocks:{},assets:{},stockBasis:{},loanDebt:0,inventory:{},businesses:[],store:{name:'',slots:3,listings:[],revenue:0,expenses:0,sales:0},salaryAt:0,tipAt:0,loanAt:0,earned:0,lost:0,games:0,wins:0,cooldowns:{},protectionUntil:0,protectionAt:0};}
function packBusiness(b={}){return[b.id||'',b.type||'',b.name||'',Number(b.level)||1,Number(b.lines)||1,Number(b.storageSlots)||12,Number(b.quality)||1,Number(b.speed)||1,Number(b.batch)||1,Number(b.lastProduced)||Date.now(),Number(b.revenue)||0,Number(b.expenses)||0];}
function unpackBusiness(v){if(!Array.isArray(v))return v&&typeof v==='object'?v:null;return{id:v[0]||'',type:v[1]||'',name:v[2]||'',level:Number(v[3])||1,lines:Number(v[4])||1,storageSlots:Number(v[5])||12,quality:Number(v[6])||1,speed:Number(v[7])||1,batch:Number(v[8])||1,lastProduced:Number(v[9])||Date.now(),revenue:Number(v[10])||0,expenses:Number(v[11])||0};}
function packStore(s={}){return[String(s.name||''),Math.max(3,Number(s.slots)||3),(Array.isArray(s.listings)?s.listings:[]).map(l=>[l.code||'',Number(l.qty)||0,Number(l.price)||0]),Number(s.revenue)||0,Number(s.expenses)||0,Number(s.sales)||0];}
function unpackStore(v){if(!Array.isArray(v))return v&&typeof v==='object'?v:{name:'',slots:3,listings:[],revenue:0,expenses:0,sales:0};return{name:String(v[0]||''),slots:Math.max(3,Number(v[1])||3),listings:(Array.isArray(v[2])?v[2]:[]).map(l=>Array.isArray(l)?{code:l[0]||'',qty:Number(l[1])||0,price:Number(l[2])||0}:l).filter(Boolean),revenue:Number(v[3])||0,expenses:Number(v[4])||0,sales:Number(v[5])||0};}
function packUser(s){return{b:s.balance,v:s.vault,sh:s.shares,st:s.stocks||{},as:s.assets||{},sb:s.stockBasis||{},ld:Math.max(0,Number(s.loanDebt)||0),iv:s.inventory||{},bz:(Array.isArray(s.businesses)?s.businesses:[]).slice(0,12).map(packBusiness),sr:packStore(s.store),sa:s.salaryAt,ta:s.tipAt,la:s.loanAt||0,e:s.earned,l:s.lost,g:s.games,w:s.wins,c:s.cooldowns||{},pu:s.protectionUntil||0,pa:s.protectionAt||0};}
function unpackUser(x={}){const legacyShares=Math.max(0,Number(x.sh??0)||0);const stocks=x.st&&typeof x.st==='object'&&!Array.isArray(x.st)?Object.fromEntries(Object.entries(x.st).filter(([,q])=>Number(q)>0).map(([k,q])=>[String(k).toUpperCase(),Number(q)])):(legacyShares>0?{NVRS:legacyShares}:{});const assetsRaw=x.as&&typeof x.as==='object'&&!Array.isArray(x.as)?x.as:{};const assets={};for(const[code,qty]of Object.entries(assetsRaw)){const n=Number(qty);if(Number.isFinite(n)&&n>0)assets[String(code).toUpperCase()]=n;}if(assets.LAND){assets.HOUSE=(assets.HOUSE||0)+assets.LAND;delete assets.LAND;}if(assets.CAR){assets.SEDAN=(assets.SEDAN||0)+assets.CAR;delete assets.CAR;}if(assets.PLANE){assets.JET=(assets.JET||0)+assets.PLANE;delete assets.PLANE;}const stockBasisRaw=x.sb&&typeof x.sb==='object'&&!Array.isArray(x.sb)?x.sb:{};const stockBasis=Object.fromEntries(Object.entries(stockBasisRaw).filter(([,v])=>Number(v)>0).map(([k,v])=>[String(k).toUpperCase(),Number(v)]));return{balance:Number(x.b??START_BALANCE)||0,vault:Math.max(0,Number(x.v??0)||0),shares:Math.max(0,Number(stocks.NVRS||legacyShares)||0),stocks,assets,stockBasis,loanDebt:Math.max(0,Number(x.ld??0)||0),inventory:x.iv&&typeof x.iv==='object'&&!Array.isArray(x.iv)?x.iv:{},businesses:(Array.isArray(x.bz)?x.bz:[]).slice(0,12).map(unpackBusiness).filter(Boolean),store:unpackStore(x.sr),salaryAt:Math.max(0,Number(x.sa??0)||0),tipAt:Math.max(0,Number(x.ta??0)||0),loanAt:Math.max(0,Number(x.la??0)||0),earned:Math.max(0,Number(x.e??0)||0),lost:Math.max(0,Number(x.l??0)||0),games:Math.max(0,Number(x.g??0)||0),wins:Math.max(0,Number(x.w??0)||0),protectionUntil:Math.max(0,Number(x.pu??0)||0),protectionAt:Math.max(0,Number(x.pa??0)||0),cooldowns:x.c&&typeof x.c==='object'&&!Array.isArray(x.c)?Object.fromEntries(Object.entries(x.c).filter(([name,at])=>/^[a-z]+$/.test(name)&&Number.isFinite(Number(at))).map(([name,at])=>[name,Math.max(0,Number(at))])):{}};}
function newMarket(){const now=Date.now();return{price:100,history:[100],updatedAt:now,assetUpdatedAt:now,goldUpdatedAt:now,stockScaleVersion:1};}
// Compact market format: histories are intentionally not persisted. They are visual-only
// and are rebuilt after restart. This keeps the Discord data record far below 2,000 chars.
function packMarket(m){const companies={};if(m.companies&&typeof m.companies==='object')for(const[code,data]of Object.entries(m.companies))companies[code]=Math.max(1,Math.round(Number(data.price)||1));const assets={};if(m.assets&&typeof m.assets==='object')for(const[code,data]of Object.entries(m.assets))assets[code]=Math.max(1,Math.round(Number(data.price)||1));return{p:Math.max(1,Math.round(Number(m.price)||100)),u:Number(m.updatedAt)||Date.now(),au:Number(m.assetUpdatedAt)||Number(m.updatedAt)||Date.now(),gu:Number(m.goldUpdatedAt)||Number(m.assetUpdatedAt)||Number(m.updatedAt)||Date.now(),sv:Number(m.stockScaleVersion||1),c:companies,a:assets};}
function unpackMarket(x={}){const price=Math.max(1,Math.round(Number(x.p)||100)),companies={};if(x.c&&typeof x.c==='object'&&!Array.isArray(x.c))for(const[code,data]of Object.entries(x.c)){const raw=(data&&typeof data==='object')?data.p:data;const p=Math.max(1,Math.round(Number(raw)||1));const oldHistory=data&&typeof data==='object'&&Array.isArray(data.h)?data.h:null;companies[String(code).toUpperCase()]={price:p,history:oldHistory&&oldHistory.length?oldHistory.map(n=>Math.max(1,Math.round(Number(n)||p))).slice(-24):[p]};}const assets={};if(x.a&&typeof x.a==='object'&&!Array.isArray(x.a))for(const[code,data]of Object.entries(x.a)){const raw=(data&&typeof data==='object')?data.p:data;const p=Math.max(1,Math.round(Number(raw)||1));const oldHistory=data&&typeof data==='object'&&Array.isArray(data.h)?data.h:null;assets[String(code).toUpperCase()]={price:p,history:oldHistory&&oldHistory.length?oldHistory.map(n=>Math.max(1,Math.round(Number(n)||p))).slice(-24):[p]};}const updatedAt=Math.max(0,Number(x.u)||Date.now()),assetUpdatedAt=Math.max(0,Number(x.au)||updatedAt),goldUpdatedAt=Math.max(0,Number(x.gu)||assetUpdatedAt);return{price,history:[price],companies,assets,updatedAt,assetUpdatedAt,goldUpdatedAt,stockScaleVersion:Math.max(1,Number(x.sv)||1)};}
function enc(value){return Buffer.from(JSON.stringify(value),'utf8').toString('base64url');}
function dec(value){try{return JSON.parse(Buffer.from(String(value),'base64url').toString('utf8'));}catch{return null;}}
function parseRecord(content){const value=String(content||'');if(value.startsWith(USER_PREFIX)){const parts=value.slice(USER_PREFIX.length).split('|');if(parts.length!==3||!/^\d{15,22}$/.test(parts[0])||!/^\d{15,22}$/.test(parts[1]))return null;const payload=dec(parts[2]);return payload?{type:'user',guildId:parts[0],userId:parts[1],payload}:null;}if(value.startsWith(MARKET_PREFIX)){const rest=value.slice(MARKET_PREFIX.length),index=rest.indexOf('|');if(index<0)return null;const guildId=rest.slice(0,index),payload=dec(rest.slice(index+1));return /^\d{15,22}$/.test(guildId)&&payload?{type:'market',guildId,payload}:null;}return null;}
function digits(value){const arabic='٠١٢٣٤٥٦٧٨٩',persian='۰۱۲۳۴۵۶۷۸۹';return String(value||'').replace(/[٠-٩۰-۹]/g,d=>String(arabic.includes(d)?arabic.indexOf(d):persian.indexOf(d)));}
function parseAmount(raw,max=Infinity){let text=digits(raw).replace(/[\u200e\u200f\u202a-\u202e\u2066-\u2069]/g,'').trim().toLowerCase().replace(/[$,،]/g,'').replace(/\s+/g,' ');const nmax=Number(max),available=Number.isFinite(nmax)?Math.max(0,nmax):Infinity;if(available<=0)return NaN;if(/^(كل|الكل|كامل|all|full)$/u.test(text))return Number.isFinite(available)?available:NaN;if(/^(نص|نصف|half)$/u.test(text))return Number.isFinite(available)?Math.max(1,available/2):NaN;if(/^(ربع|quarter)$/u.test(text))return Number.isFinite(available)?Math.max(1,available/4):NaN;const suffixes=[['dc',1e33],['no',1e30],['oc',1e27],['sp',1e24],['sx',1e21],['qi',1e18],['qa',1e15],['t',1e12],['b',1e9],['m',1e6],['k',1e3],['مليار',1e9],['مليون',1e6],['الف',1e3],['ألف',1e3]];let multiplier=1;for(const[s,m]of suffixes){if(text.endsWith(s)){multiplier=m;text=text.slice(0,-s.length).trim();break;}}const amount=Number(text)*multiplier;return Number.isFinite(amount)&&amount>0&&amount<=available?amount:NaN;}
function parseShares(raw){const count=Number(digits(raw).replace(/,/g,'').trim());return Number.isFinite(count)&&count>0?count:NaN;}
function parseShareAmount(raw,max){if(/^(?:كل|الكل|كامل|all|full|نص|نصف|half|ربع|quarter)$/u.test(digits(raw).trim().toLowerCase()))return parseAmount(raw,max);const count=parseShares(raw);return Number.isFinite(count)&&count<=max?count:NaN;}
const MONEY_SUFFIXES=[[1e33,'Dc'],[1e30,'No'],[1e27,'Oc'],[1e24,'Sp'],[1e21,'Sx'],[1e18,'Qi'],[1e15,'Qa'],[1e12,'T'],[1e9,'B'],[1e6,'M']];
function money(value){const n=Number(value)||0,a=Math.abs(n);for(const[limit,suffix]of MONEY_SUFFIXES){if(a>=limit){const scaled=n/limit,d=Math.abs(scaled)>=100?0:Math.abs(scaled)>=10?1:2;return`$${scaled.toFixed(d)}${suffix}`;}}return`$${Math.round(n).toLocaleString('en-US')}`;}
function shortMoney(value){const n=Number(value)||0,a=Math.abs(n);for(const[limit,suffix]of MONEY_SUFFIXES){if(a>=limit)return`$${(n/limit).toFixed(Math.abs(n/limit)>=100?0:1)}${suffix}`;}if(a>=1e3)return`$${(n/1e3).toFixed(1)}K`;return money(n);}
function commandCooldownLeft(state,name,now=Date.now()){return Math.max(0,Number(state.cooldowns?.[name]||0)+COMMAND_CD-now);}
function setCommandCooldown(state,name,now=Date.now()){if(!state.cooldowns||typeof state.cooldowns!=='object')state.cooldowns={};state.cooldowns[name]=now;}
function formatDuration(ms){const total=Math.max(0,Math.ceil(Number(ms)/1000)),minutes=Math.floor(total/60),seconds=total%60;return minutes?`${minutes}:${String(seconds).padStart(2,'0')}`:`${seconds}ث`;}
function cooldownStatus(ms){return ms<=0?'🟢 متاح':`🔴 الوقت الباقي ${formatDuration(ms)}`;}
module.exports={USER_PREFIX,MARKET_PREFIX,START_BALANCE,COMMAND_CD,SALARY_CD,TIP_CD,MARKET_STEP,LOAN_CD,LOAN_AMOUNT,MAX_BET,ROB_CD,PROTECTION_DURATION,clamp,newUser,packUser,unpackUser,newMarket,packMarket,unpackMarket,enc,parseRecord,digits,parseAmount,parseShares,parseShareAmount,money,shortMoney,commandCooldownLeft,setCommandCooldown,formatDuration,cooldownStatus};
